AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'lib/aws-activejob-sqs.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'