AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'tasks/release/**/*'

Gemspec/RequireMFA:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/aws-activejob-sqs.rb'
    - 'spec/aws-activejob-sqs_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
